# html lang
language: en

# main menu navigation
menu:
  Home: /
  Archives: archives
  Category: categories
  Tags: tags
  About: about

logo: /blog/img/at-ico.svg

# 文章小部件
postMeta:
  author: true
  date: true
  tags: true
  # TODO
  category: true

post:
  toc_title: CONTENT

tagCloud:
  enable: true
  bgEnable: true
  # bg: '#000'
  # ‘/blog’ 是项目的根路径 默认是‘／’
  bg: url('/blog/img/bg-1.png')

excerpt_link: Read More
# Miscelaneous
favicon: /favicon.ico

# copyright
startYear: 2016

# archive_type: 'monthly'

# stylesheets loaded in the <head>
stylesheets:
- /css/main.css
- /font-awesome-4.7.0/css/font-awesome.min.css
- /fancybox-3.0/dist/jquery.fancybox.min.css
# - 'dist/main.76c96d7053d8.css'

# scripts loaded in the end of the body
scripts:
- /libs/jquery-3.1.1.min.js

scripts_foot:
- /js/main.js
- /fancybox-3.0/dist/jquery.fancybox.min.js

disqus:
  disqus_shortname: lencx

analytics:
  google_analytics: UA-92360738-1
