# html lang
# language: en

# main menu navigation
menu:
  Home: /
  Archives: archives
  Categories: categories
  Tags: tags
  About: about

logo: /blog/img/at-ico.png

# widget (文章小部件)
postMeta:
  author: true # 作者
  date: true # 日期
  tags: true # 标签
  category: true # 分类

post:
  # 文章目录标题
  toc_title: CONTENT
  # 阅读全文
  excerpt_link: Read More

sidebar:
  tagCloud:
    enable: true
    # 是否开启背景（可用图片或直接设置背景色）
    bgEnable: true
    # bg: '#000'
    # ‘/blog’ 是项目的根路径 默认是‘／’
    bg: url('/blog/img/bg-1.png')
  archives: true
  categories: true
  recent_posts:
    enable: true
    num: 5


# Miscelaneous
favicon: /favicon.ico

# Site creation time(copyright)
since: 2017

# stylesheets loaded in the <head>
stylesheets:
# - /css/main.css
- /dist/theme.1e328056a6d9.css
- /font-awesome-4.7.0/css/font-awesome.min.css
- /fancybox-3.0/dist/jquery.fancybox.min.css

# scripts loaded in the end of the body
scripts:
- /libs/jquery-3.1.1.min.js

scripts_foot:
# - /js/main.js
- /dist/main.589b81d2e06f.js
- /fancybox-3.0/dist/jquery.fancybox.min.js

disqus:
  disqus_shortname: # your shortname

analytics:
  google_analytics: # analytics id

social:
  github: # your@github
  email: # your@email
  facebook: # your@facebook
  twitter: # your@twitter
  stact_overflow: 
